#######################################
# GLOBAL PLANNER — A*
#######################################
planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]

    GridBased:
      plugin: 'nav2_navfn_planner/NavfnPlanner' # In Iron and older versions, "/" was used instead of "::"
      use_astar: true                           # Whether to use A* (true) or Dijkstra (false)  
      allow_unknown: true
      tolerance: 0.5

#######################################
# CONTROLLER — Regulated Pure Pursuit
#######################################
controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    costmap_update_timeout: 0.3
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    odom_topic: "odom"
    odom_duration: 0.3

    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: "general_goal_checker"
    controller_plugins: "FollowPath"

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 8.0

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.30
      yaw_goal_tolerance: 0.30
      stateful: true      

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.7
      lookahead_dist: 0.7
      min_lookahead_dist: 0.4
      max_lookahead_dist: 1.2
      lookahead_time: 0.5
      rotate_to_heading_angular_vel: 1.0
      transform_tolerance: 0.5
      approach_velocity_scaling_dist: 0.6
      use_collision_detection: false
      max_allowed_time_to_collision_up_to_carrot: 2.0
      use_approach_linear_velocity_scaling: true
      min_linear_vel: 0.05
      max_linear_accel: 1.5
      max_linear_decel: -2.5
      max_angular_vel: 1.5
      min_obstacle_dist: 0.5
      allow_reversing: false
      use_rotate_to_heading: true
      use_cost_regulated_linear_speed: true
      regulated_linear_scaling_min_speed: 0.06
      regulated_linear_scaling_min_distance: 0.4

#######################################
# BEHAVIOR SERVER (recoveries)
#######################################
behavior_server:
  ros__parameters:
    use_sim_time: false
    transform_tolerance: 0.2
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    cycle_frequency: 10.0

    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint

    behavior_plugins: ["spin","backup","drive_on_heading","wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"

#######################################
# BT NAVIGATOR
#######################################
bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.5
    # default_nav_to_pose_bt_xml: "/home/raisa/dev-2025/src/raisa_bringup/config/default.xml"
    # default_nav_through_poses_bt_xml: "/home/raisa/dev-2025/src/raisa_bringup/config/default.xml"
    # default_nav_to_pose_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml"
    # default_nav_through_poses_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml"

#######################################
# GLOBAL COSTMAP
#######################################
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_link
      update_frequency: 1.0
      publish_frequency: 1.0
      resolution: 0.05
      robot_radius: 0.4

      track_unknown_space: true
      rolling_window: false
      width: 50
      height: 50
      plugins: ["static_layer","obstacle_layer","inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true 

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /laserscan          
          data_type: LaserScan
          marking: true
          clearing: true
          max_obstacle_height: 2.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6
        cost_scaling_factor: 2.0

#######################################
# LOCAL COSTMAP
#######################################
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 5.0
      publish_frequency: 2.0
      resolution: 0.05
      robot_radius: 0.7

      rolling_window: true
      width: 6
      height: 6
      plugins: ["obstacle_layer","inflation_layer"]
      track_unknown_space: false
      footprint_clearing_enabled: true
      plugins: ["obstacle_layer","inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        observation_persistence: 0.5
        scan:
          topic: /laserscan
          data_type: LaserScan
          marking: true
          clearing: true
          max_obstacle_height: 2.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 1.0
        cost_scaling_factor: 4.0
